In [2]:
from cassandra.io.libevreactor import LibevConnection
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from cassandra.query import SimpleStatement, BatchStatement
import csv
import os
import pandas as pd
from application_logging.logger import App_Logger
import shutil
from File_operations.schema_reader import read_schema

In [3]:
cloud_config= {
                                'secure_connect_bundle': 'secure-connect-ineuron.zip'
                        }
auth_provider = PlainTextAuthProvider('FfdDwAlGnqNUwQSlnZHEXhZg', '-WT.2BcPIAquAyRmrPQrI6-DT3IydQ1nT,IRTkorOWI1pUsxhZNYbxJMYRqFXjg+TFpB0Iox7fkfw74Nqpo9cWSp-OgmQ57CFYJb0OCiHDr7_79ULfWcNHEN3G+4tued')
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)

session = cluster.connect()

In [20]:
data=pd.read_csv('UCI_Credit_Card.csv')

In [25]:
session.execute('drop table ccdp.training_database;')

InvalidRequest: Error from server: code=2200 [Invalid query] message="Table 'ccdp.training_database' doesn't exist"

In [8]:
session.execute('create table ccdp.training_database  \
                                ( "ID" float,"LIMIT_BAL" float,"SEX" float,"EDUCATION" float, \
                                "MARRIAGE" float,"AGE" float,"PAY_0" float,"PAY_2" float, \
                                "PAY_3" float,"PAY_4" float,"PAY_5" float,"PAY_6" float, \
                                "BILL_AMT1" float,"BILL_AMT2" float,"BILL_AMT3" float, \
                                "BILL_AMT4" float,"BILL_AMT5" float,"BILL_AMT6" float, \
                                "PAY_AMT1" float,"PAY_AMT2" float,"PAY_AMT3" float, \
                                "PAY_AMT4" float,"PAY_AMT5" float,"PAY_AMT6" float, "Defaulted" float, \
                                primary key("ID"))')

In [22]:
for i in data.iterrows():
    print(i)

(0, ID                                1
LIMIT_BAL                     20000
SEX                               2
EDUCATION                         2
MARRIAGE                          1
AGE                              24
PAY_0                             2
PAY_2                             2
PAY_3                            -1
PAY_4                            -1
PAY_5                            -2
PAY_6                            -2
BILL_AMT1                      3913
BILL_AMT2                      3102
BILL_AMT3                       689
BILL_AMT4                         0
BILL_AMT5                         0
BILL_AMT6                         0
PAY_AMT1                          0
PAY_AMT2                        689
PAY_AMT3                          0
PAY_AMT4                          0
PAY_AMT5                          0
PAY_AMT6                          0
default.payment.next.month        1
Name: 0, dtype: int64)
(1, ID                                 2
LIMIT_BAL                     120000
SEX                                2
EDUCATION                          2
MARRIAGE                           2
AGE                               26
PAY_0                             -1
PAY_2                              2
PAY_3                              0
PAY_4                              0
PAY_5                              0
PAY_6                              2
BILL_AMT1                       2682
BILL_AMT2                       1725
BILL_AMT3                       2682
BILL_AMT4                       3272
BILL_AMT5                       3455
BILL_AMT6                       3261
PAY_AMT1                           0
PAY_AMT2                        1000
PAY_AMT3                        1000
PAY_AMT4                        1000
PAY_AMT5                           0
PAY_AMT6                        2000
default.payment.next.month         1
Name: 1, dtype: int64)
(2, ID                                3
LIMIT_BAL                     90000
SEX                               2
EDUCATION                         2
MARRIAGE                          2
AGE                              34
PAY_0                             0
PAY_2                             0
PAY_3                             0
PAY_4                             0
PAY_5                             0
PAY_6                             0
BILL_AMT1                     29239
BILL_AMT2                     14027
BILL_AMT3                     13559
BILL_AMT4                     14331
BILL_AMT5                     14948
BILL_AMT6                     15549
PAY_AMT1                       1518
PAY_AMT2                       1500
PAY_AMT3                       1000
PAY_AMT4                       1000
PAY_AMT5                       1000
PAY_AMT6                       5000
default.payment.next.month        0
Name: 2, dtype: int64)
(3, ID                                4
LIMIT_BAL                     50000
SEX                               2
EDUCATION                         2
MARRIAGE                          1
AGE                              37
PAY_0                             0
PAY_2                             0
PAY_3                             0
PAY_4                             0
PAY_5                             0
PAY_6                             0
BILL_AMT1                     46990
BILL_AMT2                     48233
BILL_AMT3                     49291
BILL_AMT4                     28314
BILL_AMT5                     28959
BILL_AMT6                     29547
PAY_AMT1                       2000
PAY_AMT2                       2019
PAY_AMT3                       1200
PAY_AMT4                       1100
PAY_AMT5                       1069
PAY_AMT6                       1000
default.payment.next.month        0
Name: 3, dtype: int64)
(4, ID                                5
LIMIT_BAL                     50000
SEX                               1
EDUCATION                         2
MARRIAGE                          1
AGE                              57
PAY_0                            -1
PAY_2                             0
PAY_3                            -1
PAY_4                             0
PAY_5                             0
PAY_6                             0
BILL_AMT1                      8617
BILL_AMT2                      5670
BILL_AMT3                     35835
BILL_AMT4                     20940
BILL_AMT5                     19146
BILL_AMT6                     19131
PAY_AMT1                       2000
PAY_AMT2                      36681
PAY_AMT3                      10000
PAY_AMT4                       9000
PAY_AMT5                        689
PAY_AMT6                        679
default.payment.next.month        0
Name: 4, dtype: int64)
(5, ID                                6
LIMIT_BAL                     50000
SEX                               1
EDUCATION                         1
MARRIAGE                          2
AGE                              37
PAY_0                             0
PAY_2                             0
PAY_3                             0
PAY_4                             0
PAY_5                             0
PAY_6                             0
BILL_AMT1                     64400
BILL_AMT2                     57069
BILL_AMT3                     57608
BILL_AMT4                     19394
BILL_AMT5                     19619
BILL_AMT6                     20024
PAY_AMT1                       2500
PAY_AMT2                       1815
PAY_AMT3                        657
PAY_AMT4                       1000
PAY_AMT5                       1000
PAY_AMT6                        800
default.payment.next.month        0
Name: 5, dtype: int64)
(6, ID                                 7
LIMIT_BAL                     500000
SEX                                1
EDUCATION                          1
MARRIAGE                           2
AGE                               29
PAY_0                              0
PAY_2                              0
PAY_3                              0
PAY_4                              0
PAY_5                              0
PAY_6                              0
BILL_AMT1                     367965
BILL_AMT2                     412023
BILL_AMT3                     445007
BILL_AMT4                     542653
BILL_AMT5                     483003
BILL_AMT6                     473944
PAY_AMT1                       55000
PAY_AMT2                       40000
PAY_AMT3                       38000
PAY_AMT4                       20239
PAY_AMT5                       13750
PAY_AMT6                       13770
default.payment.next.month         0
Name: 6, dtype: int64)
(7, ID                                 8
LIMIT_BAL                     100000
SEX                                2
EDUCATION                          2
MARRIAGE                           2
AGE                               23
PAY_0                              0
PAY_2                             -1
PAY_3                             -1
PAY_4                              0
PAY_5                              0
PAY_6                             -1
BILL_AMT1                      11876
BILL_AMT2                        380
BILL_AMT3                        601
BILL_AMT4                        221
BILL_AMT5                       -159
BILL_AMT6                        567
PAY_AMT1                         380
PAY_AMT2                         601
PAY_AMT3                           0
PAY_AMT4                         581
PAY_AMT5                        1687
PAY_AMT6                        1542
default.payment.next.month         0
Name: 7, dtype: int64)
(8, ID                                 9
LIMIT_BAL                     140000
SEX                                2
EDUCATION                          3
MARRIAGE                           1
AGE                               28
PAY_0                              0
PAY_2                              0
PAY_3                              2
PAY_4                              0
PAY_5                              0
PAY_6                              0
BILL_AMT1                      11285
BILL_AMT2                      14096
BILL_AMT3                      12108
BILL_AMT4                      12211
BILL_AMT5                      11793
BILL_AMT6                       3719
PAY_AMT1                        3329
PAY_AMT2                           0
PAY_AMT3                         432
PAY_AMT4                        1000
PAY_AMT5                        1000
PAY_AMT6                        1000
default.payment.next.month         0
Name: 8, dtype: int64)
(9, ID                               10
LIMIT_BAL                     20000
SEX                               1
EDUCATION                         3
MARRIAGE                          2
AGE                              35
PAY_0                            -2
PAY_2                            -2
PAY_3                            -2
PAY_4                            -2
PAY_5                            -1
PAY_6                            -1
BILL_AMT1                         0
BILL_AMT2                         0
BILL_AMT3                         0
BILL_AMT4                         0
BILL_AMT5                     13007
BILL_AMT6                     13912
PAY_AMT1                          0
PAY_AMT2                          0
PAY_AMT3                          0
PAY_AMT4                      13007
PAY_AMT5                       1122
PAY_AMT6                          0
default.payment.next.month        0
Name: 9, dtype: int64)
(10, ID                                11
LIMIT_BAL                     200000
SEX                                2
EDUCATION                          3
MARRIAGE                           2
AGE                               34
PAY_0                              0
PAY_2                              0
PAY_3                              2
PAY_4                              0
PAY_5                              0
PAY_6                             -1
BILL_AMT1                      11073
BILL_AMT2                       9787
BILL_AMT3                       5535
BILL_AMT4                       2513
BILL_AMT5                       1828
BILL_AMT6                       3731
PAY_AMT1                        2306
PAY_AMT2                          12
PAY_AMT3                          50
PAY_AMT4                         300
PAY_AMT5                        3738
PAY_AMT6                          66
default.payment.next.month         0
Name: 10, dtype: int64)
(11, ID                                12
LIMIT_BAL                     260000
SEX                                2
EDUCATION                          1
MARRIAGE                           2
AGE                               51
PAY_0                             -1
PAY_2                             -1
PAY_3                             -1
PAY_4                             -1
PAY_5                             -1
PAY_6                              2
BILL_AMT1                      12261
BILL_AMT2                      21670
BILL_AMT3                       9966
BILL_AMT4                       8517
BILL_AMT5                      22287
BILL_AMT6                      13668
PAY_AMT1                       21818
PAY_AMT2                        9966
PAY_AMT3                        8583
PAY_AMT4                       22301
PAY_AMT5                           0
PAY_AMT6                        3640
default.payment.next.month         0
Name: 11, dtype: int64)
(12, ID                                13
LIMIT_BAL                     630000
SEX                                2
EDUCATION                          2
MARRIAGE                           2
AGE                               41
PAY_0                             -1
PAY_2                              0
PAY_3                             -1
PAY_4                             -1
PAY_5                             -1
PAY_6                             -1
BILL_AMT1                      12137
BILL_AMT2                       6500
BILL_AMT3                       6500
BILL_AMT4                       6500
BILL_AMT5                       6500
BILL_AMT6                       2870
PAY_AMT1                        1000
PAY_AMT2                        6500
PAY_AMT3                        6500
PAY_AMT4                        6500
PAY_AMT5                        2870
PAY_AMT6                           0
default.payment.next.month         0
Name: 12, dtype: int64)
(13, ID                               14
LIMIT_BAL                     70000
SEX                               1
EDUCATION                         2
MARRIAGE                          2
AGE                              30
PAY_0                             1
PAY_2                             2
PAY_3                             2
PAY_4                             0
PAY_5                             0
PAY_6                             2
BILL_AMT1                     65802
BILL_AMT2                     67369
BILL_AMT3                     65701
BILL_AMT4                     66782
BILL_AMT5                     36137
BILL_AMT6                     36894
PAY_AMT1                       3200
PAY_AMT2                          0
PAY_AMT3                       3000
PAY_AMT4                       3000
PAY_AMT5                       1500
PAY_AMT6                          0
default.payment.next.month        1
Name: 13, dtype: int64)
(14, ID                                15
LIMIT_BAL                     250000
SEX                                1
EDUCATION                          1
MARRIAGE                           2
AGE                               29
PAY_0                              0
PAY_2                              0
PAY_3                              0
PAY_4                              0
PAY_5                              0
PAY_6                              0
BILL_AMT1                      70887
BILL_AMT2                      67060
BILL_AMT3                      63561
BILL_AMT4                      59696
BILL_AMT5                      56875
BILL_AMT6                      55512
PAY_AMT1                        3000
PAY_AMT2                        3000
PAY_AMT3                        3000
PAY_AMT4                        3000
PAY_AMT5                        3000
PAY_AMT6                        3000
default.payment.next.month         0
Name: 14, dtype: int64)
(15, ID                               16
LIMIT_BAL                     50000
SEX                               2
EDUCATION                         3
MARRIAGE                          3
AGE                              23
PAY_0                             1
PAY_2                             2
PAY_3                             0
PAY_4                             0
PAY_5                             0
PAY_6                             0
BILL_AMT1                     50614
BILL_AMT2                     29173
BILL_AMT3                     28116
BILL_AMT4                     28771
BILL_AMT5                     29531
BILL_AMT6                     30211
PAY_AMT1                          0
PAY_AMT2                       1500
PAY_AMT3                       1100
PAY_AMT4                       1200
PAY_AMT5                       1300
PAY_AMT6                       1100
default.payment.next.month        0
Name: 15, dtype: int64)
(16, ID                               17
LIMIT_BAL                     20000
SEX                               1
EDUCATION                         1
MARRIAGE                          2
AGE                              24
PAY_0                             0
PAY_2                             0
PAY_3                             2
PAY_4                             2
PAY_5                             2
PAY_6                             2
BILL_AMT1                     15376
BILL_AMT2                     18010
BILL_AMT3                     17428
BILL_AMT4                     18338
BILL_AMT5                     17905
BILL_AMT6                     19104
PAY_AMT1                       3200
PAY_AMT2                          0
PAY_AMT3                       1500
PAY_AMT4                          0
PAY_AMT5                       1650
PAY_AMT6                          0
default.payment.next.month        1
Name: 16, dtype: int64)
(17, ID                                18
LIMIT_BAL                     320000
SEX                                1
EDUCATION                          1
MARRIAGE                           1
AGE                               49
PAY_0                              0
PAY_2                              0
PAY_3                              0
PAY_4                             -1
PAY_5                             -1
PAY_6                             -1
BILL_AMT1                     253286
BILL_AMT2                     246536
BILL_AMT3                     194663
BILL_AMT4                      70074
BILL_AMT5                       5856
BILL_AMT6                     195599
PAY_AMT1                       10358
PAY_AMT2                       10000
PAY_AMT3                       75940
PAY_AMT4                       20000
PAY_AMT5                      195599
PAY_AMT6                       50000
default.payment.next.month         0
Name: 17, dtype: int64)
(18, ID                                19
LIMIT_BAL                     360000
SEX                                2
EDUCATION                          1
MARRIAGE                           1
AGE                               49
PAY_0                              1
PAY_2                             -2
PAY_3                             -2
PAY_4                             -2
PAY_5                             -2
PAY_6                             -2
BILL_AMT1                          0
BILL_AMT2                          0
BILL_AMT3                          0
BILL_AMT4                          0
BILL_AMT5                          0
BILL_AMT6                          0
PAY_AMT1                           0
PAY_AMT2                           0
PAY_AMT3                           0
PAY_AMT4                           0
PAY_AMT5                           0
PAY_AMT6                           0
default.payment.next.month         0
Name: 18, dtype: int64)
(19, ID                                20
LIMIT_BAL                     180000
SEX                                2
EDUCATION                          1
MARRIAGE                           2
AGE                               29
PAY_0                              1
PAY_2                             -2
PAY_3                             -2
PAY_4                             -2
PAY_5                             -2
PAY_6                             -2
BILL_AMT1                          0
BILL_AMT2                          0
BILL_AMT3                          0
BILL_AMT4                          0
BILL_AMT5                          0
BILL_AMT6                          0
PAY_AMT1                           0
PAY_AMT2                           0
PAY_AMT3                           0
PAY_AMT4                           0
PAY_AMT5                           0
PAY_AMT6                           0
default.payment.next.month         0
Name: 19, dtype: int64)
(20, ID                                21
LIMIT_BAL                     130000
SEX                                2
EDUCATION                          3
MARRIAGE                           2
AGE                               39
PAY_0                              0
PAY_2                              0
PAY_3                              0
PAY_4                              0
PAY_5                              0
PAY_6                             -1
BILL_AMT1                      38358
BILL_AMT2                      27688
BILL_AMT3                      24489
BILL_AMT4                      20616
BILL_AMT5                      11802
BILL_AMT6                        930
PAY_AMT1                        3000
PAY_AMT2                        1537
PAY_AMT3                        1000
PAY_AMT4                        2000
PAY_AMT5                         930
PAY_AMT6                       33764
default.payment.next.month         0
Name: 20, dtype: int64)
(21, ID                                22
LIMIT_BAL                     120000
SEX                                2
EDUCATION                          2
MARRIAGE                           1

In [ ]:

session.execute('insert into ccdp.training_database \
                                                ( "ID","LIMIT_BAL","SEX","EDUCATION","MARRIAGE","AGE","PAY_0","PAY_2", \
                                                "PAY_3","PAY_4","PAY_5","PAY_6","BILL_AMT1","BILL_AMT2","BILL_AMT3", \
                                                "BILL_AMT4","BILL_AMT5","BILL_AMT6","PAY_AMT1","PAY_AMT2","PAY_AMT3", \
                                                "PAY_AMT4","PAY_AMT5","PAY_AMT6","Defaulted") VALUES \
                                                (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
                                                        ,[      float(item[0]),
                                                                float(item[1]),
                                                                float(item[2]),
                                                                float(item[3]),
                                                                float(item[4]),
                                                                float(item[5]),
                                                                float(item[6]),
                                                                float(item[7]),
                                                                float(item[8]),
                                                                float(item[9]),
                                                                float(item[10]),
                                                                float(item[11]),
                                                                float(item[12]),
                                                                float(item[13]),
                                                                float(item[14]),
                                                                float(item[15]),
                                                                float(item[16]),
                                                                float(item[17]),
                                                                float(item[18]),
                                                                float(item[19]),
                                                                float(item[20]),
                                                                float(item[21]),
                                                                float(item[22]),
                                                                float(item[23]),
                                                                float(item[24])])

In [23]:
session.execute("COPY domains FROM 'UCI_Credit_Card.csv' WITH HEADER = true")

SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 'COPY' ([COPY]...)">

In [ ]:
with open("UCI_Credit_Card.csv", "r") as data:
    for d in data:
        columns=fare.split(",")
        pickup=datetime.datetime.strptime(columns[0],"%Y-%m-%d").date()
        dropoff=datetime.datetime.strptime(columns[1],"%Y-%m-%d").date()
        distance=columns[2]
        fare=columns[3]
        p_long=columns[4]
        p_lat=columns[5]
        d_long=columns[6]
        d_lat=columns[7]

        session.execute(prepared, [pickup,dropoff,distance,fare,p_long,p_lat,d_long,d_lat])

#closing the file
data.close()

#closing Cassandra connection
session.shutdown()

In [28]:
session.execute('drop table ccdp.prediction_database;')

In [26]:
session.execute('drop table ccdp.training_database;')

OperationTimedOut: errors={'3b7abe6a-2898-4bd5-9882-286bb753ac9a-asia-south1.db.astra.datastax.com:29042:6b0a6727-0997-4e01-80c2-199c4c86ccf9': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=3b7abe6a-2898-4bd5-9882-286bb753ac9a-asia-south1.db.astra.datastax.com:29042:6b0a6727-0997-4e01-80c2-199c4c86ccf9

In [27]:
list(session.execute('select count(*) from ccdp.training_database'))

InvalidRequest: Error from server: code=2200 [Invalid query] message="table ccdp.training_database does not exist"